### ISSUE TITLE
Failed to lookup view "pages/settings"

### ISSUE THREAD

**Issue by seanvree** [denysvitali/sonos-web#23]
Windows 10E

I can launch NPM and get to the UI, but nothing really works, 

When I click on settings, I get this:

```
Error: Failed to lookup view "pages/settings" in views directory "c:\sonos-web/src/views/"
    at EventEmitter.render (c:\sonos-web\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (c:\sonos-web\node_modules\express\lib\response.js:966:7)
    at app.get (c:\sonos-web\server.js:201:9)
    at Layer.handle [as handle_request] (c:\sonos-web\node_modules\express\lib\router\layer.js:95:5)
    at next (c:\sonos-web\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (c:\sonos-web\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (c:\sonos-web\node_modules\express\lib\router\layer.js:95:5)
    at c:\sonos-web\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (c:\sonos-web\node_modules\express\lib\router\index.js:335:12)
    at next (c:\sonos-web\node_modules\express\lib\router\index.js:275:10)
```

**Comment by denysvitali** [comment]
Dear @seanvree ,
that's an expected output because the Settings page (as well as he Queue page) isn't developed yet.

The project is still in an alpha state and it's not really intended for an everyday use.
Btw, soundcloud and youtube should work properly

**Comment by seanvree** [comment]
got it! THanks!

**Comment by denysvitali** [comment]
Btw, in a few minutes I'll post a better version, which may fix many bugs

**Comment by denysvitali** [comment]
Done, you can `git pull`, `npm install` again and `npm start` 👍

**Comment by seanvree** [comment]
@denysvitali got it! Is there supposed to be an option for me to choose my Room?  Mine is blank. Nothing to choose

**Comment by denysvitali** [comment]
Nope, not at the moment unfortunately. It is planned though

**Comment by seanvree** [comment]
@denysvitali  all good man!  Looks good! Keep it up!
